public with sharing class ProviderConstants {
    public ProviderConstants() {

    }
    public static final string SUCCESS='SUCCESS';
    public static final string ERROR='ERROR';
    public static final string INSERTSUCCESS='SUCCESSFULLY INSERTED';
    public static final string UPDATESUCCESS='SUCCESSFULLY UPDATED';
    public static final string DELETESUCCESS='SUCCESSFULLY DELETED';
    public static final string APPROVED='APPROVED';
    public static final string CASEWORKERSUBMITTED='caseworker submitted';
    public static final string APPLICATION_ACTIVITY_INCOMPLETE='INCOMPLETE';
    public static final string APPLICATION_ACTIVITY_PENDING='PENDING';
    public static final string APPLICATION_ACTIVITY_SUCCESS_TODISPLAY='Completed';
    public static final string APPLICATION_ACTIVITY_DRAFT_TODISPLAY='Draft';}